# Generated by Django 3.0.5 on 2021-03-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('AppointmentId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=60)),
                ('doctorname', models.CharField(choices=[('Uma', 'Uma'), ('kumar', 'kumar')], max_length=60)),
                ('PatId', models.IntegerField()),
                ('DoctId', models.IntegerField()),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctorId', models.AutoField(primary_key=True, serialize=False)),
                ('doctorName', models.CharField(max_length=10)),
                ('doctorEmail', models.EmailField(max_length=254)),
                ('doctorContact', models.CharField(max_length=30)),
                ('doctorGender', models.CharField(max_length=20)),
                ('doctorAge', models.IntegerField()),
                ('doctorsalary', models.CharField(max_length=20)),
                ('doctorAddress', models.CharField(max_length=50)),
                ('doctorPassword', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Doctor',
            },
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('hrId', models.AutoField(primary_key=True, serialize=False)),
                ('hrName', models.CharField(max_length=10)),
                ('hrPassword', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'HR',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientId', models.AutoField(primary_key=True, serialize=False)),
                ('patientName', models.CharField(max_length=30)),
                ('patientEmail', models.EmailField(max_length=254)),
                ('patientPassword', models.CharField(max_length=30)),
                ('patientContact', models.CharField(max_length=30)),
                ('patientAddress', models.CharField(max_length=50)),
                ('patientGender', models.CharField(max_length=20)),
                ('patientAge', models.IntegerField()),
            ],
            options={
                'db_table': 'Patient',
            },
        ),
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('ReceptionistId', models.AutoField(primary_key=True, serialize=False)),
                ('ReceptionistName', models.CharField(max_length=10)),
                ('ReceptionistEmail', models.EmailField(max_length=254)),
                ('ReceptionistContact', models.CharField(max_length=30)),
                ('ReceptionistAddress', models.CharField(max_length=50)),
                ('ReceptionistGender', models.CharField(max_length=20)),
                ('ReceptionistAge', models.IntegerField()),
                ('Receptionistsalary', models.CharField(max_length=20)),
                ('ReceptionistPassword', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Receptionist',
            },
        ),
    ]
