# Generated by Django 3.0.5 on 2021-03-28 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('PrescriptionId', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('symptoms', models.CharField(max_length=20)),
                ('discription', models.CharField(max_length=50)),
                ('medicine', models.CharField(max_length=20)),
                ('treatement', models.CharField(max_length=20)),
                ('patient_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Prescription',
            },
        ),
    ]
